services:
  tbls:
    image: ghcr.io/wuweiflow/tbls-fms:v0.08
    env_file:
      - .env
    working_dir: /work
    volumes:
      - ./.tbls.yml:/work/.tbls.yml:ro
      - ./docs:/work/docs
    command:
      - doc
      - --force
      - --rm-dist
